# -*- mode: ruby -*-
# vi: set ft=ruby :

DOMAIN = ".vagrant.dev"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.landrush.enabled = true
  config.vm.network "private_network", type: "dhcp"
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "puppetmaster" do |puppetmaster|
    puppetmaster.vm.hostname = "puppetmaster" + DOMAIN
    puppetmaster.vm.provision "file", source: "site.pp", destination: "/tmp/site.pp"
    puppetmaster.vm.provision :shell, :path => "puppetmaster.sh"
  end

  config.vm.define "primary" do |primary|
    primary.vm.hostname = "primary" + DOMAIN
    primary.vm.provision "puppet_server" do |puppet|
      puppet.puppet_server = "puppetmaster.vagrant.dev"
      puppet.options = ["--waitforcert=60", "--verbose"]
    end
  end

  config.vm.define "standby" do |standby|
    standby.vm.hostname = "standby" + DOMAIN
    standby.vm.provision "puppet_server" do |puppet|
      puppet.puppet_server = "puppetmaster.vagrant.dev"
      puppet.options = ["--waitforcert=60", "--verbose"]
    end
  end

end
